version: "3.9"

services:
  app:
    build:
      context: . #use the current directory
      args:
        - DEV=true #set a build argument called DEV to true
    ports:
      - "8000:8000" #port mappings: this maps port 8000 on local machine to 8000 in the container
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=dev-db
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      #set the initial database config and user for our local server
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
